version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
